# Generated by Django 5.0.6 on 2024-06-19 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='Contains the name of Project', max_length=100)),
                ('creation_time', models.DateTimeField(auto_now_add=True, help_text='Project creation time.')),
                ('completion_time', models.DateTimeField(help_text='Project completion time', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(help_text='Contains the Task Name under Project', max_length=70)),
                ('description', models.TextField(help_text='Task Description')),
                ('time_estimate', models.IntegerField(help_text='Time in hours required to complete task')),
                ('completed', models.BooleanField(default=False, help_text='Status of Task Completion')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectp.project')),
            ],
        ),
    ]
